name: Build Arch Linux ARM Disk Image
on: [push]
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo ${{ github.workspace }}/build.sh 
      - run: sudo ${{ github.workspace }}/boot.exp
      - uses: actions/upload-artifact@v2
        with:
          name: alarm
          path: |
            archlinux.qcow2
            flash0.img
            flash1.img
