---
name: "nightly"

on: 
  push:
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight UTC

jobs:
  nightly:
    name: "Arch Linux ARM nightly build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - run: sudo ${{ github.workspace }}/build.sh 

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Arch Linux ARM M1"
          files: |
            archlinux.tar.gz
